#description: test YAML
#login: root
#passwd: abc123
#host: artemis13.datadomain.com
description: test YAML
login: james
passwd: jamescth
host: 192.168.180.224
timeout: 10
tests:
  - - test1
    - CMD pwd
    - CMD ls
  - - test2
    - CMD ls -l
    - CMD whoami EXPECT james
    - CMD whoami NOTEXPECT root
